# Generated by Django 5.2.7 on 2025-11-02 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=255, verbose_name='Tên môn học')),
                ('subject_code', models.CharField(max_length=50, verbose_name='Mã môn học')),
                ('class_name', models.CharField(max_length=100, verbose_name='Tên lớp')),
                ('class_start_time', models.DateTimeField(verbose_name='Giờ vào lớp (tính trễ)')),
                ('session_start_time', models.DateTimeField(verbose_name='Giờ bắt đầu điểm danh (mở camera)')),
                ('end_time', models.DateTimeField(verbose_name='Giờ kết thúc điểm danh')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_sv', models.CharField(max_length=50)),
                ('ho_ten', models.CharField(max_length=255)),
                ('gio_vao', models.DateTimeField(verbose_name='Giờ vào')),
                ('status', models.CharField(choices=[('Đúng giờ', 'Đúng giờ'), ('Trễ giờ', 'Trễ giờ')], default='Đúng giờ', max_length=10)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='app.attendancesession')),
            ],
            options={
                'unique_together': {('session', 'ma_sv')},
            },
        ),
    ]
